
export const GET_CATEGORY_GROUP="GET_CATEGORY_GROUP";
export const GET_CATEGORY="GET_CATEGORY";
export const GET_CATEGORY_BY_ID_GROUP="GET_CATEGORY_BY_ID_GROUP";
export const GET_ALL_STORE="GET_ALL_STORE";
export const GET_ALL_PRODUCT="GET_ALL_PRODUCT";
export const FIND_PRODUCT_BY_ID="FIND_PRODUCT_BY_ID";