export const FIND_PRODUCT_BY_ID="FIND_PRODUCT_BY_ID";
export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_TO_CART="REMOVE_TO_CART";
export const UPDATE_TO_CART="UPDATE_TO_CART";
export const REMOVE_ALL_CART="REMOVE_ALL_CART";